/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIApp */

#ifndef _Included_JNIApp
#define _Included_JNIApp
#ifdef __cplusplus
extern "C" {
#endif
#undef JNIApp_FOCUS_TRAVERSABLE_UNKNOWN
#define JNIApp_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JNIApp_FOCUS_TRAVERSABLE_DEFAULT
#define JNIApp_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JNIApp_FOCUS_TRAVERSABLE_SET
#define JNIApp_FOCUS_TRAVERSABLE_SET 2L
#undef JNIApp_TOP_ALIGNMENT
#define JNIApp_TOP_ALIGNMENT 0.0f
#undef JNIApp_CENTER_ALIGNMENT
#define JNIApp_CENTER_ALIGNMENT 0.5f
#undef JNIApp_BOTTOM_ALIGNMENT
#define JNIApp_BOTTOM_ALIGNMENT 1.0f
#undef JNIApp_LEFT_ALIGNMENT
#define JNIApp_LEFT_ALIGNMENT 0.0f
#undef JNIApp_RIGHT_ALIGNMENT
#define JNIApp_RIGHT_ALIGNMENT 1.0f
#undef JNIApp_serialVersionUID
#define JNIApp_serialVersionUID -7644114512714619750i64
#undef JNIApp_serialVersionUID
#define JNIApp_serialVersionUID 4613797578919906343i64
#undef JNIApp_INCLUDE_SELF
#define JNIApp_INCLUDE_SELF 1L
#undef JNIApp_SEARCH_HEAVYWEIGHTS
#define JNIApp_SEARCH_HEAVYWEIGHTS 1L
#undef JNIApp_serialVersionUID
#define JNIApp_serialVersionUID -2728009084054400034i64
#undef JNIApp_serialVersionUID
#define JNIApp_serialVersionUID -5836846270535785031i64
#undef JNIApp_serialVersionUID
#define JNIApp_serialVersionUID 8121819178012096909i64
/*
 * Class:     JNIApp
 * Method:    initCppSide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNIApp_initCppSide
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIApp
 * Method:    oneFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIApp_oneFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
